const actCinema = {
    GET_MOVIE: "GET_MOVIE",
    SET_MOVIE: "SET_MOVIE",

    SET_SELECTION_CINEMA: "SET_SELECTION_CINEMA",
    GET_SELECTION_CINEMA: "GET_SELECTION_CINEMA",

    SET_SELECTION_THEATER: "SET_SELECTION_THEATER",
    GET_SELECTION_THEATER: "GET_SELECTION_THEATER",

    SET_SELECTION_RATE: "SET_SELECTION_RATE",

    SET_SELCTION_DAY: "SET_SELECTION_DAY"

}
export default actCinema